// Rewrite the instructions in your own words

// Write the objectives and the tests

// Write the pseudocode



// paste your JS generated by blockly below here
var input, list, acronyms, i;


input = window.prompt('Insert A phrase');
list = input.split(' ');
acronyms = '';
for (var i_index in list) {
  i = list[i_index];
  acronyms += String(i.charAt(0));
}
acronyms = acronyms.toUpperCase();
window.alert(acronyms);