// Rewrite the instructions in your own words

// Write the objectives and the tests

// Write the pseudocode


//
//create a variable for winner and looser each
//create a variable to check the balance between winner and looser
//create another variable called computer and set is to the list game name i.e rock, paper, scissor
//create random integer that match the number of listed game name i.e rock, paper, scissor
//set a loop to 3 time repetition
//create inlist item that equate to prompt with a message to play
//create logi function to determine winner or looser
//print the result.
//


// paste your JS generated by blockly below here

var and, computer, win, loose, x, hit, rc;

function mathRandomInt(a, b) {
  if (a > b) {
    // Swap a and b to ensure a is smaller.
    var c = a;
    a = b;
    b = c;
  }
  return Math.floor(Math.random() * (b - a + 1) + a);
}


and = '-';
computer = 'rock. scissor,paper'.split(',');
win = 0;
loose = 0;
for (var count = 0; count < 3; count++) {
  x = mathRandomInt(1, 3);
  if (computer[(x - 1)] == window.prompt('play ')) {
    win = (typeof win == 'number' ? win : 0) + 1;
    loose = (typeof loose == 'number' ? loose : 0) + 1;
  }
}
hit = 'you loose';
rc = 'you win';
if (win > loose) {
  window.alert(rc + win + and + loose);
}
window.alert(hit + win + and + loose);

0 == 0;